import type { Metadata } from "next";
import Link from "next/link";
// import { Geist } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
/* Keeping for future ref */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={''}>
      <body>
        <Sidebar/>
        {children}</body>
    </html>
  );
}

function Sidebar() {
  return (
    <div className="sidebar">
      <h1>Chiz.pink</h1>
      <nav>
        <Link href="/">Home</Link>
        <Link href="/checklist">Checklist</Link>
        <Link href="/characters">Characters</Link>
        <Link href="/inventory">Inventory</Link>
      </nav>
    </div>
  );
}
