import { Character } from "@/types/character"

import { EnumRarity } from "@/data/items"
import {
	ascSilhouetteSet,
	confessionalFLowerSeed,
	dressSleevesOfVanity,
	talentTarotSet,
} from "@/data/items/materials"
import { EnumArcType } from "@/data/arcs"
import { EnumCharacterElement } from "@/data/characters"

export const lacrimosa: Character = {
	id: "lacrimosa",
	imageSrc: "lacrimosa.png",
	name: "Lacrimosa",
	description:
		"Holds the record for most maintenance requests submitted by BAC staff.",
	rarity: EnumRarity.Epic,
	element: EnumCharacterElement.CHAOS,
	arcType: EnumArcType.Liquid,
	ascensionMaterialSet: ascSilhouetteSet,
	ascensionBossMaterial: confessionalFLowerSeed,
	talentMaterialSet: talentTarotSet,
	talentBossMaterial: dressSleevesOfVanity,
	abilities: {
		basicAttack: {
			name: "Sweet and Sour",
			description: [
				{
					section: "Basic Attack: Tomato Metal",
					description:
						"Swings her Frying Pan, performing up to <dn>5</> consecutive attacks. The projectile generated by the 2nd attack can be shattered by subsequent attacks, causing an explosion and dealing extra Chaos DMG.",
				},
				{
					section: "Basic Attack: Tomato Percussion",
					description:
						"Manipulates Red Jelly, performing up to <dn>5</> consecutive attacks.\nTriggers the Nightmare status when Lacrimosa's Basic Attack hits, dealing damage equal to x% of Lacrimosa's ATK per second for xs.\nNightmare can stack up to 10 times.\nInflicts 1 stack of Nightmare for each damage instance that hits when a single Basic Attack deals multiple instances of damage. Removes 1 stack of Nightmare when the target receives healing.",
				},
				{
					section: "Flavor Varitation",
					description:
						"Flavor Variation can be used at any time via the Aim button.\nTosses her Frying Pan and performs a flying kick forward when using Tomato Metal, dealing <dn>1</> instance of Chaos DMG to each target hit. Switches her attack module to Sweet and Sour.\nLeaps into the air and slams the ground, dealing <dn>1</> instance of AoE Chaos DMG when using Sweet and Sour. Switches her attack module to Tomato Metal.\n\nThe current Basic Attack style determines the attack pattern of Working Day Judgement.",
				},
				{
					section: "Basic Attack: Devilish Inspiration",
					description:
						"Hold to enter Aim mode. Deals 1 instance of Chaos DMG to an enemy in the crosshair and learns their combat technique.\nTemporarily forgets Morning Tomato and uses the learned technique upon successful learning.\nLearned techniques are stored permanently in Lacrimosa's memory. New techniques can be learned to replace existing ones, or Lacrimosa can actively forget a technique on the Skill page to recall Morning Tomato.",
				},
				{
					section: "Basic Attack: Lycopersicum Meteors",
					description:
						"Manipulates Esper Ability Constructs in the air and plunges, dealing <dn>1</> instance of Chaos DMG to an area upon impact. Increases DMG based on fall height, up to 100%.",
				},
				{
					section: "Critical Riposte: fff Rest",
					description:
						"Triggers when using Basic Attacks after a Critical Dodge. Seizes the opening created by the enemy's missed attack and violently hurls a large amount of Red Jelly onto the enemy's head, dealing <dn>6</> instances of Chaos DMG to an area and reducing Break.",
				},
				{
					section: "Nightmare",
					description:
						"Inflicts Nightmare on the target when attacks hit, up to 10 stacks.\nInflicts 1 stack of Nightmare per damage instance when a single Basic Attack deals multiple instances of damage.",
				},
			],
			maxLvl: 10,
		},
		skill: {
			name: "Morning Tomato",
			description: [
				{
					section: "Skill: Morning Tomato",
					description:
						"Ah… Achoo! Throws a barrage of unfinished Esper Ability Constructs, dealing <dn>1</> instance of Chaos DMG to all targets within the area and inflicting Nightmare on the targets.\nCombos into the <dn>5</>th instance of Tomato Metal or Tomato Percussion after casting Morning Tomato.",
				},
				{
					section: "Redirect Skill: Devilish Gift",
					description:
						"Lacrimosa... can do it too.\nLacrimosa uses her Esper Ability to copy and cast an enemy's skill, triggering the corresponding additional effects. The skill duration matches that of the original owner. During the cast, Lacrimosa cannot move, but she can manually cancel the cast or switch to another character. Lacrimosa takes damage if she is attacked during the cast.\nCasting Devilish Gift grants Lacrimosa a percentage of the original skill owner's ATK.",
				},
			],
			maxLvl: 10,
		},
		ultimate: {
			name: "Working Day Judgement",
			description: [
				{
					description:
						"Controls the Truck when using Tomato Metal, dealing 10 instances of Chaos DMG to an area and inflicting Nightmare on all targets in range.",
				},
				{
					description:
						"Dismantles the Car when using Tomato Percussion, dealing 5 instances of Chaos DMG to an area and inflicting Nightmare on all targets in range.",
				},
			],
			maxLvl: 10,
		},
		support: {
			name: "Microwake",
			description: [
				{
					description:
						"Lacrimosa get this done, and Lacrimosa get to sleep… Manipulates Esper Ability Constructs, dealing <dn>1</> instance of Chaos DMG to an area.",
				},
			],
			maxLvl: 10,
		},
		passive1: {
			name: "Tomato Banquet",
			description: [
				{
					description:
						"<sh>Discord Enhancement:</> Deals additional DMG equal to 400% of ATK to the target when Discord is triggered, if the target is already Broken.",
				},
			],
			maxLvl: 1,
		},
		passive2: {
			name: "Sleep In",
			description: [
				{
					description:
						"Grants <dn>1</> additional attempt of Morning Tomato after Lacrimosa uses Tomato Metal or Tomato Percussion <dn>5</> times during the skill cooldown. Activates only <dn>1</> time per skill cooldown.",
				},
			],
			maxLvl: 1,
		},
		lifeSkill1: {
			name: "Chef Tomato",
			description: [
				{
					description:
						"<sh>Level 1:</> Lacrimosa increases dish prices by <dn>1%</> for each Dessert tag on dishes.",
				},
				{
					description:
						"<sh>Level 2:</> Lacrimosa reduces ingredient consumption rate by <dn>1%</>.",
				},
				{
					description:
						"<sh>Level 3:</> In Owner's Selection, a special dish \"Special Tomato Juice\" appears, made by adding tomato juice to a glass.",
				},
				{
					description:
						"<sh>Level 4:</> Lacrimosa reduces ingredient consumption rate by <dn>1%</>.",
				},
				{
					description:
						"<sh>Level 5:</> Lacrimosa increases dish prices by <dn>1.5%</> for every 2 Dessert tags on dishes.",
				},
			],
			maxLvl: 5,
		},
		lifeSkill2: {
			name: "Exclusive Bat-efit",
			description: [
				{
					description:
						"<sh>Level 1:</> Increases Fons and Paw-Paw Coins obtained from Pink Paws Heist settlement by <dn>15%</> while Lacrimosa is in the team (Cannot exceed the cap).",
				},
				{
					description:
						"<sh>Level 2:</> Increases the bonus to Fons and Paw-Paw Coins obtained from Pink Paws Heist settlement to <dn>20%</> while Lacrimosa is in the team (Cannot exceed the cap).",
				},
			],
			maxLvl: 2,
		},
	},
}
